-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "prices"."tokens" add column "calledCoinGeckoMinutes" boolean
--  null default 'false';
